config/routes.rb
Rails.application.routes.draw do             
  # Routes for the User account:

  # SIGN UP FORM
  get("/user_sign_up", { :controller => "user_authentication", :action => "sign_up_form" })        
  # CREATE RECORD
  post("/insert_user", { :controller => "user_authentication", :action => "create"  })
      
  # EDIT PROFILE FORM        
  get("/edit_user_profile", { :controller => "user_authentication", :action => "edit_profile_form" })       
  # UPDATE RECORD
  post("/modify_user", { :controller => "user_authentication", :action => "update" })
  
  # DELETE RECORD
  get("/cancel_user_account", { :controller => "user_authentication", :action => "destroy" })

  # ------------------------------

  # SIGN IN FORM
  get("/user_sign_in", { :controller => "user_authentication", :action => "sign_in_form" })
  # AUTHENTICATE AND STORE COOKIE
  post("/user_verify_credentials", { :controller => "user_authentication", :action => "create_cookie" })
  
  # SIGN OUT        
  get("/user_sign_out", { :controller => "user_authentication", :action => "destroy_cookies" })
             
  #------------------------------

  #------------------------------

  root "shoes#index"

  get "/shoes/liked_shoes" => "shoes#liked_shoes", as: :liked_shoes
  
  resources :shoes
  # --------------------------------------------------------
  # #CREATE 
  # post "/shoes" => "shoes#create", as: :shoes
  # get "/shoes/new" => "shoes#new", as: :new_shoe

  # #READ
  # get "/shoes" => "shoes#index"
  # get "/shoes/:id" => "shoes#show", as: :shoe

  # #UPDATE
  # patch "/shoes/:id" => "shoes#update"
  # get "/shoes/:id/edit" => "shoes#edit", as: :edit_shoe

  # #DELETE
  # delete "/shoes/:id" => "shoes#destroy"


  # Likes
  get "/user_liked_shoe" => "likes#user_likes"
  get "/user_unliked_shoe/:id" => "likes#user_unliked"

  #Delete 
  get "/delete/:id" => "shoes#destroy"
  get "/delete_comment/:id" => "comments#destroy"

  #Comments 
  get "/comments" => "comments#index"
  get "/edit_comments" => "comments#edit"
  post "/edit_comments/:id" => "comments#update_comment"
  post "/insert_comment" => "comments#create_comment"

  #Liked Shoes
  # get "/liked_shoes" => "shoes#liked_shoes"

end

app/views/bootstrap/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "Collex", root_path, class: "navbar-brand text-success font-weight-bold" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Sign in", "/user_sign_in", class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Sign up", "/user_sign_up", class: "nav-link" %>
          </li>
        </ul>
        <!--
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
    </nav>

app/views/bootstrap/_user_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "Collex", root_path, class: "navbar-brand text-success font-weight-bold" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Profile", "/edit_user_profile", class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Feed", shoes_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Add Shoe", new_shoe_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Liked Shoes", "/shoes/liked_shoes" , class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Sign Out", "/user_sign_out", class: "nav-link" %>
          </li>
        </ul>
        <!--
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
</nav>