config/routes.rb
Rails.application.routes.draw do             
  # Routes for the User account:

  # SIGN UP FORM
  get("/user_sign_up", { :controller => "user_authentication", :action => "sign_up_form" })        
  # CREATE RECORD
  post("/insert_user", { :controller => "user_authentication", :action => "create"  })
      
  # EDIT PROFILE FORM        
  get("/edit_user_profile", { :controller => "user_authentication", :action => "edit_profile_form" })       
  # UPDATE RECORD
  post("/modify_user", { :controller => "user_authentication", :action => "update" })
  
  # DELETE RECORD
  get("/cancel_user_account", { :controller => "user_authentication", :action => "destroy" })

  # ------------------------------

  # SIGN IN FORM
  get("/user_sign_in", { :controller => "user_authentication", :action => "sign_in_form" })
  # AUTHENTICATE AND STORE COOKIE
  post("/user_verify_credentials", { :controller => "user_authentication", :action => "create_cookie" })
  
  # SIGN OUT        
  get("/user_sign_out", { :controller => "user_authentication", :action => "destroy_cookies" })
             
  #------------------------------

  #------------------------------

  root "shoes#index"

  get "/shoes/liked_shoes" => "shoes#liked_shoes", as: :liked_shoes
  
  resources :shoes
  # --------------------------------------------------------
  # #CREATE 
  # post "/shoes" => "shoes#create", as: :shoes
  # get "/shoes/new" => "shoes#new", as: :new_shoe

  # #READ
  # get "/shoes" => "shoes#index"
  # get "/shoes/:id" => "shoes#show", as: :shoe

  # #UPDATE
  # patch "/shoes/:id" => "shoes#update"
  # get "/shoes/:id/edit" => "shoes#edit", as: :edit_shoe

  # #DELETE
  # delete "/shoes/:id" => "shoes#destroy"


  # Likes
  get "/user_liked_shoe" => "likes#user_likes"
  get "/user_unliked_shoe/:id" => "likes#user_unliked"

  #Delete 
  get "/delete/:id" => "shoes#destroy"
  get "/delete_comment/:id" => "comments#destroy"

  #Comments 
  get "/comments" => "comments#index"
  get "/edit_comments" => "comments#edit"
  post "/edit_comments/:id" => "comments#update_comment"
  post "/insert_comment" => "comments#create_comment"

  #Liked Shoes
  # get "/liked_shoes" => "shoes#liked_shoes"

end

app/models/shoe.rb
# == Schema Information
#
# Table name: shoes
#
#  id          :integer          not null, primary key
#  authentic   :boolean
#  deadstock   :boolean
#  description :text
#  image       :string
#  shoe_type   :string
#  size        :integer
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  owner_id    :integer
#
class Shoe < ApplicationRecord
  belongs_to :owner, class_name: "User", foreign_key: "owner_id"

  has_many :comments, class_name: "Comment", foreign_key: "author_id"
  has_many :likes, class_name: "Like", foreign_key: "fan_id"

  mount_uploader :image, ImageUploader
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  def index
    @shoes = Shoe.order(created_at: :desc)

    respond_to do |format|
      format.json { render json: @movies }

      format.html
    end
  end

  def new
    @shoe = Shoe.new
    shoes_and_sizes()
  end

  def create
    @shoe = Shoe.new(shoe_attributes)

    if @shoe.valid?
      @shoe.save
      redirect_to "/shoes", notice: "Shoe created successfully"
    else
      render "new"
    end
  end

  def show
    @shoe = Shoe.find(params.fetch(:id))
  end

  def edit
    @shoe = Shoe.find(params.fetch(:id))
    shoes_and_sizes()
  end

  def update
    @shoe = Shoe.find(params.fetch(:id))

    if @shoe.update(shoe_attributes)
      redirect_to @shoe, notice: "Movie updated successfully"
    else
      render "edit"
    end
  end

  def destroy
    #@shoe = Shoe.find(params.fetch(:id))

    #@shoe.destroy

    the_id = params.fetch(:id)
    shoe = Shoe.where({ :id => the_id }).first

    shoe.delete

    redirect_to shoes_url, notice: "Shoe deleted successfully"
    #redirect_to("/movies", { :notice => "Movie deleted successfully."} )
  end

  def liked_shoes

    render "shoes/liked_shoes.html.erb"
  end

  private 

  def shoes_and_sizes
    @sizes = []
    @shoe_types = ['Mens', 'Womens', 'Big Kids', 'Little Kids', 'Toddlers']

    (1..18).each do |count| 
      @sizes.push(count.to_s)
    end 
  end

  def shoe_attributes
    shoe_attributes = params.require(:shoe).permit(:owner_id, :image, :title, :description, :deadstock, :authentic)
  end
end

app/views/shoes/_form.html.erb
<%= form_with(model: @shoe) do |form| %>

  <div>
    <%= form.label :owner_id %>
    <%= form.select :owner_id, [@current_user.id] %>
  </div>

  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :shoe_type %>
    <%= form.select :shoe_type, @shoe_types %>
  </div>

  <div>
    <%= form.label :size %>
    <%= form.select :size, @sizes  %>
  </div>

  <div>
    <%= form.label :deadstock %>
    <%= form.check_box :deadstock %>    
  </div>

  <div>
    <%= form.label :authentic %>
    <%= form.check_box :authentic %>
  </div>

  <div>
    <%= form.button "Add to Collection", class: "btn-success"%>
  </div>

<% end %>

app/views/shoes/_shoe.html.erb
<div class="card">
<% if @current_user != nil %>
  <div class="card-header">
    <%= link_to "#{shoe.owner.username}'s shoe", shoe, class: "h3" %>
  </div>

<% else %>
<% end %>

  <div class="card-body">

    <div class="row">
	    <div class="col">
	      <dl>
	        <dt class="">Image</dt>
	        <div class="btn btn-block"></div>
	        <dd class="text-center"><img src="<%= shoe.image %>" height="280px"></dd>
	      </dl>
	    </div>
	
	    <div class="col">
	    <dl>
	      <% if @current_user != nil %>
	      <dt>
	        Owner
	      </dt>
	      <dd>
	        <%= shoe.owner.username %>
	      </dd>
	      <% else %>
	      <% end %>
	
	      <dt>
	        Title
	      </dt>
	      <dd>
	        <%= shoe.title %>
	      </dd>
	
	      <dt>
	        Description
	      </dt>
	      <dd>
	        <%= shoe.description %>
	      </dd>
	
	      <dt>
	        Shoe type
	      </dt>
	      <dd>
	        <%= shoe.shoe_type %>
	      </dd>
	
	      <dt>
	        Size
	      </dt>
	      <dd>
	        <%= shoe.size %>
	      </dd>
	
	      <dt>
	        Deadstock 
	      </dt>
	      <dd>
	        <%= shoe.deadstock %>
	      </dd>
	
	      <dt>
	        Authentic
	      </dt>
	      <dd>
	        <%= shoe.authentic %>
	      </dd>
	
	      </dl>
	    </div>
    </div>

  </div>

  <div class="btn btn-block card-footer">
    Last updated <%= time_ago_in_words(shoe.updated_at) %> ago
  </div>
</div>

<div class="row"><div class="d-grid btn btn-large btn-block"></div></div>

app/views/shoes/_user_liked_shoes.html.erb
<% if shoe.shoe == nil %>

<% else %>

<div class="card">
  <div class="card-header">
    <%#= link_to "Shoe ##{shoe.shoe.id}", liked_shoes_path, class: "h3" %>
    <a href="/shoes/<%= shoe.shoe.id %>"><h3 class="text-success">View</h3></a>
  </div>

  <div class="card-body">
    <div class="row">
    <div class="col align-self-center">
      <dl>
        <dt>Image</dt>
        <dd><img src="<%= shoe.shoe.image %>" height="280px"></dd>
      </dl>
    </div>

    <div class="col">
      <dl>
        <dt>
          Owner
        </dt>
        <dd>
          <%= shoe.shoe.owner.username %>
        </dd>

        <dt>
          Title
        </dt>
        <dd>
          <%= shoe.shoe.title %>
        </dd>

        <dt>
          Description
        </dt>
        <dd>
          <%= shoe.shoe.description %>
        </dd>

        <dt>
          Shoe type
        </dt>
        <dd>
          <%= shoe.shoe.shoe_type %>
        </dd>

        <dt>
          Size
        </dt>
        <dd>
          <%= shoe.shoe.size %>
        </dd>

        <dt>
          Deadstock 
        </dt>
        <dd>
          <%= shoe.shoe.deadstock %>
        </dd>

        <dt>
          Authentic
        </dt>
        <dd>
          <%= shoe.shoe.authentic %>
        </dd>

      </dl>
    </div>
    </div>

    <div class="row">
    <% if shoe.shoe.owner_id == @current_user.id %>
      <div class="col">
        <div class="d-grid">
          <%= link_to edit_shoe_path(shoe.shoe.id), class: "btn btn-warning btn-lg btn-block" do %>
            <span><i class="fa-regular fa-pen-to-square"></i></span>
          <% end %>
        </div>
      </div>
      <div class="col">
        <div class="d-grid">
          <%#= link_to shoe, method: :delete, class: "btn btn-danger btn-lg btn-block" do %>
          <a href="/delete/<%= shoe.shoe.id %>" method="post" class="btn btn-danger btn-lg btn-block">
            <span><i class="fa-regular fa-trash-can"></i></span>
          </a>
          <%# end %>
        </div>
      </div>
      <% else%>
      <% end %>
    </div>
    
    <div class="row"><div class="d-grid btn btn-large btn-block"></div></div> <!-- Added an empty row to have buttons equally seperated -->

    <div class="row">
      <div class="col">
          <div class="d-grid">
            <form action="/user_unliked_shoe/<%= shoe.id%>" style="cursor: pointer">
              <button class="btn btn-success btn-lg btn-block"><span><i class="fa-sharp fa-regular fa-heart fa-rotate-180"></i></span></button>
            </form>
          </div>
        </div>

      <div class="col">
        <div class="d-grid">
          <%#= link_to edit_shoe_path(shoe), class: "btn btn-dark btn-lg btn-block" do %>
              <a href="/" class="btn btn-dark btn-lg btn-block"><span><i class="fa-sharp fa-solid fa-house"></i></span></a>
            </form>
          <%# end %>
        </div>
      </div>
    </div>
  </div>

  <div class="card-footer">
    Last updated <%= time_ago_in_words(shoe.updated_at) %> ago
  </div>
</div>
<div class="row"><div class="d-grid btn btn-large btn-block"></div></div>
<% end %>

app/views/shoes/_user_shoe.html.erb
<div class="card">
  <div class="card-header">
    <%= link_to "View", shoe, class: "h3 text-success" %>
  </div>

  <div class="card-body">

  <!-- Testing beyong this point -->
  <div class="row">
    <div class="col align-self-center">
      <dl>
        <dt>Image</dt>
        <dd><img src="<%= shoe.image %>" height="280px"></dd>
      </dl>
    </div>
  <!-- Testing above this point -->

    <div class="col">
      <dl>
      <dt>
          Owner
        </dt>
        <dd>
          <%= shoe.owner.username %>
        </dd>
        <dt>
          Title
        </dt>
        <dd>
          <%= shoe.title %>
        </dd>

        <dt>
          Description
        </dt>
        <dd>
          <%= shoe.description %>
        </dd>

        <dt>
          Shoe type
        </dt>
        <dd>
          <%= shoe.shoe_type %>
        </dd>

        <dt>
          Size
        </dt>
        <dd>
          <%= shoe.size %>
        </dd>

        <dt>
          Deadstock 
        </dt>
        <dd>
          <%= shoe.deadstock %>
        </dd>

        <dt>
          Authentic
        </dt>
        <dd>
          <%= shoe.authentic %>
        </dd>

      </dl>
    </div>
   </div>

    <div class="row">
    <% if shoe.owner_id == @current_user.id %>
      <div class="col">
        <div class="d-grid">
          <%= link_to edit_shoe_path(shoe), class: "btn btn-warning btn-lg btn-block" do %>
            <span><i class="fa-regular fa-pen-to-square"></i></span>
          <% end %>
        </div>
      </div>
      <div class="col">
        <div class="d-grid">
          <%#= link_to shoe, method: :delete, class: "btn btn-danger btn-lg btn-block" do %>
          <a href="/delete/<%= shoe.id %>" method="post" class="btn btn-danger btn-lg btn-block">
            <span><i class="fa-regular fa-trash-can"></i></span>
          </a>
          <%# end %>
        </div>
      </div>
     <% else %>
     <% end %>
    </div>
    
    <div class="row"><div class="d-grid btn btn-large btn-block"></div></div> <!-- Added an empty row to have buttons equally seperated -->

    <div class="row">
    <% user_like =  @current_user.likes.where(shoe_id: shoe.id)[0] %>
    <% if user_like == nil %>
     <div class="col">
        <div class="d-grid">
          <form action="/user_liked_shoe" style="cursor: pointer">
            <input type="hidden" name="shoe_id" value="<%= shoe.id %>">
            <button class="btn btn-success btn-lg btn-block"<span><i class="fa-sharp fa-regular fa-heart"></i></span></button>
          </form>
        </div>
      </div>
    <% else %>
    <div class="col">
        <div class="d-grid">
          <form action="/user_unliked_shoe/<%= shoe.id%>" style="cursor: pointer">
            <button class="btn btn-success btn-lg btn-block"><span><i class="fa-sharp fa-regular fa-heart fa-rotate-180"></i></span></button>
          </form>
        </div>
      </div>
    <% end %>
      <div class="col">
        <div class="d-grid">
          <%#= link_to edit_shoe_path(shoe), class: "btn btn-dark btn-lg btn-block" do %>
              <a href="/comments" class="btn btn-dark btn-lg btn-block"><span><i class="fa-sharp fa-regular fa-comment"></i></span></a>
            </form>
          <%# end %>
        </div>
      </div>
    </div>
  </div>

  <div class="card-footer">
    Last updated <%= time_ago_in_words(shoe.updated_at) %> ago
  </div>
</div>

<div class="row"><div class="d-grid btn btn-large btn-block"></div></div>

app/views/shoes/edit.html.erb
<h1> Edit page </h1>

<%= render partial: "shoes/form" %>

app/views/shoes/extra.html.erb
  <table border= 1>
    <tr>
      <th> Image </th>
      <th> Title </th>
      <th> Description </th>
      <th> Shoe type </th>
      <th> Size </th>
      <th> Deadstock </th>
      <th> Authentic </th>
      <th> Created_at </th>
      <th> Updated_at </th>
      <th> Show details </th>
    </tr>
    <% @shoes.each do |shoe| %>

    <tr>
      <td> <img src="<%= shoe.image %>" width="150px" height="120"> </td>
      <td> <%= shoe.title%> </td>
      <td> <%= shoe.description %> </td>
      <td> <%= shoe.shoe_type %> </td>
      <td> <%= shoe.size %> </td>
      <td> <%= shoe.deadstock %> </td>
      <td> <%= shoe.authentic %> </td>
      <td> <%= time_ago_in_words(shoe.created_at) %> ago </td>
      <td> <%= time_ago_in_words(shoe.updated_at) %> ago </td>
      <td>
        <%= link_to "Show details", shoe %> 
      </td>
    </tr>

    <% end %>
</table>

app/views/shoes/index.html.erb
  <h1>Feed</h1>

<hr>

<div class="row">
  <% @shoes.each do |shoe| %>
    <div class="col-md-10 offset-md-1">
      <% if @current_user != nil %>
        <%= render partial: "shoes/user_shoe", locals: { shoe: shoe }%>
      <% else %>
        <%= render partial: "shoes/shoe", locals: { shoe: shoe } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shoes/liked_shoes.html.erb
<h1>Liked Shoes</h1>

<hr>

<% @current_user.likes.each do |shoe| %>
  <div class="col-md-10 offset-md-1">
      <%= render partial: "shoes/user_liked_shoes", locals: { shoe: shoe } %>
  </div>
<% end %>

app/views/shoes/new.html.erb
<h1> Add new shoes </h1>

<%= render partial: "shoes/form" %>

app/views/shoes/show.html.erb
<hr>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= render @shoe %>
  </div>
</div>